# boot.yml for Vagrant provision
--- 
- name: Vagrant internal provisioning 
  hosts: all
  become: true
  tasks:    
    - name: Create .ssh directory
      file: 
        path: "/root/.ssh"
        state: directory
    - name: Create authorized_keys file
      file: 
        path: "/root/.ssh/authorized_keys"
        state: touch
    - name: Deploy SSH public key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub')}}"
    - name: Disable Strict Host Key Checking  
      lineinfile:
        path: "/etc/ssh/ssh_config"
        regexp: '^#   StrictHostKeyChecking ask'
        line: StrictHostKeyChecking no
...
