- name: FTP server is installed
  hosts: 
    - ftpservers
  vars_files:
    - vars/defaults-template.yml
    - vars/vars.yml

  tasks:
    - name: Packages are installed
      yum:
        name: "{{ vsftpd_package }}"
        state: latest

    - name: Ensure service is started
      service:
        name: "{{ vsftpd_service }}"
        state: started
        enabled: true

    - name: Configuration file is installed
      template:
        src: templates/vsftpd.conf.j2
        dest: "{{ vsftpd_config_file }}"
        owner: root
        group: root
        mode: 0600
        setype: etc_t
      notify: restart vsftpd

    - name: firewall is installed
      yum:
        name: firewalld
        state: present

    - name: firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: FTP port is open
      firewalld:
        service: ftp
        state: enabled
        permanent: true
        immediate: true

    - name: Passive FTP data ports allowed throuh the firewall
      firewalld:
        port: 21000-21020/tcp
        state: enabled
        permanent: true
        immediate: true

  handlers:
    - name: restart vsftpd
      service:
        name: "{{ vsftpd_service }}"
        state: restarted
