# classroom.yml external 
---
- name: Classroom Configuration
  hosts: classroom
  remote_user: root
  tasks:

    - name: Install packages
      package:
        name:
          - httpd
          - chrony
          - createrepo
        state: present

    - name: Service enable,start
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: 
        - firewalld
        - httpd
        - chronyd

    - name: Chrony server 
      lineinfile:
        path: /etc/chrony.conf
        line: allow 172.25.250.0/24
      notify: restart crond

    - name: Firewall settings
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - http
        - ntp

    - name: Create directory for repository 
      file:
        path: /var/www/html/yum/repository
        recurse: yes

    - name: Sync lab 
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: 'files/labs/' , dest: '/var/www/html/labs' }
        - { src: 'files/src/' , dest: '/var/www/html/src' }
        - { src: 'files/repo/' , dest: '/var/www/html/yum/repository' } 
        - { src: 'files/git/' , dest: '/home/devops/git' }
      notify: restart httpd

    - name: Create repository 
      shell:
        cmd: createrepo_c ./
        chdir: /var/www/html/yum/repository
 
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: restart chronyd
      service:
        name: chronyd
        state: restarted
        enabled: true
...
