---
- name: Update web server
  hosts: webservers

  tasks:
    - name: Lastest httpd package installed
      yum:
        name: httpd
        state: latest
      notify:
        - Restart httpd

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        enabled: yes
        state: restarted
