---
- name: configure SOE
  hosts: all
  remote_user: devops
  become: true
  vars:
    - system_owner: someone@example.com
  tasks:
    - name: configure /etc/motd
      template: 
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
...
