# site.yml for External provision
---
- name: Global configuration
  import_playbook: plays/global.yml

- name: Workstation configuration
  import_playbook: plays/workstation.yml

- name: Classroom configuration
  import_playbook: plays/classroom.yml

- name: Access configuration
  import_playbook: plays/access.yml
...
