# site.yml for External provision
---
- name: External provisioning 
  hosts: all
  remote_user: root
  tasks:
    - name: Connection test
      ping:

- name: Global configuration
  import_playbook: plays/global.yml
...
